name: Deploy to Preprod

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: preprod-deployment
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: src/cdk/package-lock.json

      - name: Install dependencies
        run: |
          cd src/cdk
          npm ci

      - name: Debug OIDC Token Claims
        run: |
          echo "=== GitHub Context ==="
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "=== Workflow Inputs ==="
          echo "Input Branch: ${{ github.event.inputs.branch }}"
          echo "Resolved Branch: ${{ github.event.inputs.branch || github.ref_name }}"
          echo "=== Expected OIDC sub claim ==="
          echo "repo:${{ github.repository }}:ref:${{ github.ref }}"
          echo "=== Trust Policy Pattern ==="
          echo "repo:joao-doliveira/everything-at-hand:ref:refs/heads/*"

      - name: Debug AWS STS Token
        run: |
          echo "=== AWS STS Debug ==="
          # Extract account ID from role ARN
          ROLE_ARN="${{ secrets.PREPROD_DEPLOYMENT_ROLE_ARN }}"
          ACCOUNT_ID=$(echo "$ROLE_ARN" | cut -d':' -f5)
          echo "Role ARN: $ROLE_ARN"
          echo "Extracted Account ID: $ACCOUNT_ID"
          echo "OIDC Provider Account ID (from trust policy): 254192665051"
          echo "AWS Region: sa-east-1"
          echo "Session Name: GitHubActions-${{ github.run_id }}"
          # Check if account IDs match
          if [ "$ACCOUNT_ID" = "254192665051" ]; then
            echo "✅ Account IDs match - issue is elsewhere"
          else
            echo "❌ Account ID MISMATCH - this is likely the problem!"
            echo "   Role is in account: $ACCOUNT_ID"
            echo "   OIDC provider is in account: 254192665051"
          fi
          # Try to get the web identity token (this should work)
          if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ] && [ -n "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
            echo "OIDC token request URL is available"
          else
            echo "ERROR: OIDC token request environment not available"
          fi

      - name: Configure AWS Credentials for Preprod
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PREPROD_DEPLOYMENT_ROLE_ARN }}
          aws-region: sa-east-1
          role-session-name: GitHubActions-${{ github.run_id }}
          mask-aws-account-id: false

      - name: Deploy to Preprod
        run: |
          cd src/cdk
          npx cdk deploy --all --context environment=preprod --require-approval never
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch || github.ref_name }}
          PREPROD_AWS_ACCOUNT_ID: ${{ secrets.PREPROD_AWS_ACCOUNT_ID }}
